<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class PenggunaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nama' => 'Tri Anton',
                'email' => 'tri.anton@email.com',
                'tgl_lahir' => '1990-01-15',
                'nohp' => '081234567891',
                'alamat' => 'Jl. Merdeka No. 1',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('pagiseninmalas444'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Nova Ramadhan',
                'email' => 'nova.ramadhan@email.com',
                'tgl_lahir' => '1992-03-20',
                'nohp' => '081234567892',
                'alamat' => 'Jl. Sudirman No. 5',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('botaklicin123'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ignas Surya',
                'email' => 'ignas.surya@email.com',
                'tgl_lahir' => '1988-07-09',
                'nohp' => '081234567893',
                'alamat' => 'Jl. Mawar No. 3',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('hotdog999'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Erika Setiana',
                'email' => 'erika.setiana@email.com',
                'tgl_lahir' => '1995-11-30',
                'nohp' => '081234567894',
                'alamat' => 'Jl. Anggrek No. 10',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('sayaganteng123'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Indana Zulfa',
                'email' => 'indana.zulfa@email.com',
                'tgl_lahir' => '1993-05-21',
                'nohp' => '081234567895',
                'alamat' => 'Jl. Melati No. 7',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Dontol Maut',
                'email' => 'dontol.maut@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '081234567896',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'hakos baelz',
                'email' => 'baelz.hakos@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '081234564123',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ligma Boy',
                'email' => 'Ligma.Ligma@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '081234567811',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Obelia Laras',
                'email' => 'Laras@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '0812333333311',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gigi Murin',
                'email' => 'Gigi.Murin@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '081234562231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Asep Galkkok',
                'email' => 'Asep@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '099234562231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mulyon',
                'email' => 'Ijazah.Asli@email.com',
                'tgl_lahir' => '1992-09-12',
                'nohp' => '099234561131',
                'alamat' => 'Jl. We Wok No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Cecep Suryana',
                'email' => 'Cecep@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '0992322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Yukokku Roberu',
                'email' => 'Roberu@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '012322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Cecilia Immeergreen',
                'email' => 'Cecilia@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '0192322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Nanashi Mumei',
                'email' => 'Mumei.owl@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '0712322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Risu Ayunda',
                'email' => 'risu@email.com',
                'tgl_lahir' => '1996-03-01',
                'nohp' => '082112223333',
                'alamat' => 'Jl. Kacang Tanah No. 17',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('risuboss'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Moona Hoshinova',
                'email' => 'moona@email.com',
                'tgl_lahir' => '1998-02-15',
                'nohp' => '085623451234',
                'alamat' => 'Jl. Cahaya Bulan No. 8',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('moonalight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Anya Melfissa',
                'email' => 'anya@email.com',
                'tgl_lahir' => '1997-10-22',
                'nohp' => '081144556677',
                'alamat' => 'Jl. Intelijen No. 9',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('anyasecret'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Zeta Vestia',
                'email' => 'zeta@email.com',
                'tgl_lahir' => '2001-01-01',
                'nohp' => '087811223344',
                'alamat' => 'Jl. Rahasia Negara No. 1',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('zetazeta'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Regis Altare',
                'email' => 'regis@email.com',
                'tgl_lahir' => '1999-06-06',
                'nohp' => '081234123412',
                'alamat' => 'Jl. Kepemimpinan No. 99',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('leader123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Axel Syrios',
                'email' => 'axel@email.com',
                'tgl_lahir' => '1996-05-05',
                'nohp' => '089923456789',
                'alamat' => 'Jl. Gladiator No. 10',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('axelfight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Hakka Bluefield',
                'email' => 'hakka@email.com',
                'tgl_lahir' => '1995-08-20',
                'nohp' => '082211667788',
                'alamat' => 'Jl. Biru Langit No. 3',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('bluefield'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bettel Flayon',
                'email' => 'bettel@email.com',
                'tgl_lahir' => '1994-12-11',
                'nohp' => '083812345678',
                'alamat' => 'Jl. Komedi Gelap No. 6',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('jokerlife'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kaela Kovalskia',
                'email' => 'kaela@email.com',
                'tgl_lahir' => '1993-11-05',
                'nohp' => '082234567801',
                'alamat' => 'Jl. Tukang Besi No. 2',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('kaelahammer'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ollie Kureiji',
                'email' => 'ollie@email.com',
                'tgl_lahir' => '1999-02-28',
                'nohp' => '081223344800',
                'alamat' => 'Jl. Zombie Ceria No. 3',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('ollierage'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Reine Pavolia',
                'email' => 'reine@email.com',
                'tgl_lahir' => '1998-07-17',
                'nohp' => '082112348899',
                'alamat' => 'Jl. Merak Anggun No. 9',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('reinequeen'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Amelia Watson',
                'email' => 'amelia@email.com',
                'tgl_lahir' => '1996-01-06',
                'nohp' => '087788990011',
                'alamat' => 'Jl. Detektif Waktu No. 1',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('watsondetect'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gawr Gura',
                'email' => 'gura@email.com',
                'tgl_lahir' => '1995-04-20',
                'nohp' => '081122334455',
                'alamat' => 'Jl. Laut Dalam No. 7',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('gawrshark'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shirakami Fubuki',
                'email' => 'fubuki@email.com',
                'tgl_lahir' => '1993-10-11',
                'nohp' => '089922334466',
                'alamat' => 'Jl. Serigala Putih No. 5',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('foxfriend'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Sakamata Chloe',
                'email' => 'chloe@email.com',
                'tgl_lahir' => '2000-12-24',
                'nohp' => '083312345678',
                'alamat' => 'Jl. Pembersih Laut No. 6',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('sakamata'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shirogane Noel',
                'email' => 'noel@email.com',
                'tgl_lahir' => '1994-05-15',
                'nohp' => '081999223344',
                'alamat' => 'Jl. Ksatria Baja No. 88',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('noelarmor'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kazama Iroha',
                'email' => 'iroha@email.com',
                'tgl_lahir' => '2001-03-30',
                'nohp' => '081112223334',
                'alamat' => 'Jl. Samurai Desa No. 99',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('kazamawind'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shishiro Botan',
                'email' => 'botan@email.com',
                'tgl_lahir' => '1993-09-10',
                'nohp' => '084412345666',
                'alamat' => 'Jl. Singa Siber No. 23',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('botanlion'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Roberu Shiny',
                'email' => 'Shinyroberu@email.com',
                'tgl_lahir' => '1992-06-18',
                'nohp' => '081230001111',
                'alamat' => 'Jl. Barista Hangat No. 1',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('kopiroberu'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Aruran Magni',
                'email' => 'aruran@email.com',
                'tgl_lahir' => '1990-04-04',
                'nohp' => '082220002222',
                'alamat' => 'Jl. Guru Luar Angkasa No. 12',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('aruran123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Oga Kageyama',
                'email' => 'oga@email.com',
                'tgl_lahir' => '1989-09-09',
                'nohp' => '083330003333',
                'alamat' => 'Jl. Raja Iblis No. 3',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('ogaboss'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Rikka Violet',
                'email' => 'rikka@email.com',
                'tgl_lahir' => '1991-11-11',
                'nohp' => '084440004444',
                'alamat' => 'Jl. Ilmuwan Musik No. 21',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('gitaranrikka'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Izuru Kanade',
                'email' => 'izuru@email.com',
                'tgl_lahir' => '1993-03-03',
                'nohp' => '085550005555',
                'alamat' => 'Jl. Suara Merdu No. 10',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('izurusing'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Astel Leda',
                'email' => 'astel@email.com',
                'tgl_lahir' => '1997-12-24',
                'nohp' => '086660006666',
                'alamat' => 'Jl. Bintang Biru No. 8',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('astellight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Temma Shien',
                'email' => 'temma@email.com',
                'tgl_lahir' => '1992-10-10',
                'nohp' => '087770007777',
                'alamat' => 'Jl. Ksatria Cahaya No. 77',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('temmasword'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shien Kuro',
                'email' => 'shien@email.com',
                'tgl_lahir' => '1990-02-14',
                'nohp' => '088880008888',
                'alamat' => 'Jl. Bayangan Malam No. 2',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('shienfox'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gamma Noir',
                'email' => 'gamma@email.com',
                'tgl_lahir' => '1998-05-05',
                'nohp' => '089990009999',
                'alamat' => 'Jl. Cat Tumpah No. 17',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('gammacore'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
        ];

        foreach ($data as $index => &$item) {
            $item['uid'] = sprintf('00000000-0000-0000-0000-%012d', $index + 1);
        }

        DB::table('pengguna')->insert($data);

    }
}