<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class PenggunaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nama' => 'Tri Anton',
                'email' => 'tri.anton@email.com',
                'tgl_lahir' => '1990-01-15',
                'nohp' => '081234567891',
                'alamat' => 'Jl. Merdeka No. 1',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('pagiseninmalas444'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Nova Ramadhan',
                'email' => 'nova.ramadhan@email.com',
                'tgl_lahir' => '1992-03-20',
                'nohp' => '081234567892',
                'alamat' => 'Jl. Sudirman No. 5',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('botaklicin123'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ignas Surya',
                'email' => 'ignas.surya@email.com',
                'tgl_lahir' => '1988-07-09',
                'nohp' => '081234567893',
                'alamat' => 'Jl. Mawar No. 3',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('hotdog999'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Erika Setiana',
                'email' => 'erika.setiana@email.com',
                'tgl_lahir' => '1995-11-30',
                'nohp' => '081234567894',
                'alamat' => 'Jl. Anggrek No. 10',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('sayaganteng123'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Indana Zulfa',
                'email' => 'indana.zulfa@email.com',
                'tgl_lahir' => '1993-05-21',
                'nohp' => '081234567895',
                'alamat' => 'Jl. Melati No. 7',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'admin',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Dontol Maut',
                'email' => 'dontol.maut@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '081234567896',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'hakos baelz',
                'email' => 'baelz.hakos@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '081234564123',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ligma Boy',
                'email' => 'Ligma.Ligma@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '081234567811',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Obelia Laras',
                'email' => 'Laras@email.com',
                'tgl_lahir' => '1985-09-12',
                'nohp' => '0812333333311',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gigi Murin',
                'email' => 'Gigi.Murin@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '081234562231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Asep Galkkok',
                'email' => 'Asep@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '099234562231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mulyon',
                'email' => 'Ijazah.Asli@email.com',
                'tgl_lahir' => '1992-09-12',
                'nohp' => '099234561131',
                'alamat' => 'Jl. We Wok No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lapras Wave',
                'email' => 'lapras@email.com',
                'tgl_lahir' => '1998-08-08',
                'nohp' => '081200000011',
                'alamat' => 'Jl. Ajibarang Wetan No. 11, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('laprassurf'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gardevoir Grace',
                'email' => 'gardevoir@email.com',
                'tgl_lahir' => '1999-04-16',
                'nohp' => '081200000012',
                'alamat' => 'Jl. Banyumas Kulon No. 3, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('gardepsychic'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Togekiss Sky',
                'email' => 'togekiss@email.com',
                'tgl_lahir' => '2000-06-06',
                'nohp' => '081200000013',
                'alamat' => 'Jl. Kutasari No. 7, Purbalingga',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('flyhighkiss'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Blaziken Flame',
                'email' => 'blaziken@email.com',
                'tgl_lahir' => '1997-09-21',
                'nohp' => '081200000014',
                'alamat' => 'Jl. Bancar No. 4, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('blazekick'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Tyranitar Rock',
                'email' => 'tyranitar@email.com',
                'tgl_lahir' => '1996-12-01',
                'nohp' => '081200000015',
                'alamat' => 'Jl. Padamara No. 2, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('sandstorm'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Sylveon Fairy',
                'email' => 'sylveon@email.com',
                'tgl_lahir' => '2001-11-11',
                'nohp' => '081200000016',
                'alamat' => 'Jl. Somagede No. 8, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('fairybind'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Infernape Fist',
                'email' => 'infernape@email.com',
                'tgl_lahir' => '1995-05-23',
                'nohp' => '081200000017',
                'alamat' => 'Jl. Purbalingga Kidul No. 9, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('flamepunch'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Greninja Stealth',
                'email' => 'greninja@email.com',
                'tgl_lahir' => '1998-03-03',
                'nohp' => '081200000018',
                'alamat' => 'Jl. Kembaran No. 1, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('waterblade'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Garchomp Claw',
                'email' => 'garchomp@email.com',
                'tgl_lahir' => '1994-07-14',
                'nohp' => '081200000019',
                'alamat' => 'Jl. Kejobong No. 13, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('dragonrush'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Espeon Shine',
                'email' => 'espeon@email.com',
                'tgl_lahir' => '2002-02-22',
                'nohp' => '081200000020',
                'alamat' => 'Jl. Rawalo No. 10, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('futuregaze'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Cecep Suryana',
                'email' => 'Cecep@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '0992322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Yukokku Roberu',
                'email' => 'Roberu@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '012322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Cecilia Immeergreen',
                'email' => 'Cecilia@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '0192322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Nanashi Mumei',
                'email' => 'Mumei.owl@email.com',
                'tgl_lahir' => '1995-09-12',
                'nohp' => '0712322362231',
                'alamat' => 'Jl. Kenangan No. 13',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('password123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Risu Ayunda',
                'email' => 'risu@email.com',
                'tgl_lahir' => '1996-03-01',
                'nohp' => '082112223333',
                'alamat' => 'Jl. Kacang Tanah No. 17',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('risuboss'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Moona Hoshinova',
                'email' => 'moona@email.com',
                'tgl_lahir' => '1998-02-15',
                'nohp' => '085623451234',
                'alamat' => 'Jl. Cahaya Bulan No. 8',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('moonalight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Anya Melfissa',
                'email' => 'anya@email.com',
                'tgl_lahir' => '1997-10-22',
                'nohp' => '081144556677',
                'alamat' => 'Jl. Intelijen No. 9',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('anyasecret'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Zeta Vestia',
                'email' => 'zeta@email.com',
                'tgl_lahir' => '2001-01-01',
                'nohp' => '087811223344',
                'alamat' => 'Jl. Rahasia Negara No. 1',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('zetazeta'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Regis Altare',
                'email' => 'regis@email.com',
                'tgl_lahir' => '1999-06-06',
                'nohp' => '081234123412',
                'alamat' => 'Jl. Kepemimpinan No. 99',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('leader123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Axel Syrios',
                'email' => 'axel@email.com',
                'tgl_lahir' => '1996-05-05',
                'nohp' => '089923456789',
                'alamat' => 'Jl. Gladiator No. 10',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('axelfight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Hakka Bluefield',
                'email' => 'hakka@email.com',
                'tgl_lahir' => '1995-08-20',
                'nohp' => '082211667788',
                'alamat' => 'Jl. Biru Langit No. 3',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('bluefield'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bettel Flayon',
                'email' => 'bettel@email.com',
                'tgl_lahir' => '1994-12-11',
                'nohp' => '083812345678',
                'alamat' => 'Jl. Komedi Gelap No. 6',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('jokerlife'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kaela Kovalskia',
                'email' => 'kaela@email.com',
                'tgl_lahir' => '1993-11-05',
                'nohp' => '082234567801',
                'alamat' => 'Jl. Tukang Besi No. 2',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('kaelahammer'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ollie Kureiji',
                'email' => 'ollie@email.com',
                'tgl_lahir' => '1999-02-28',
                'nohp' => '081223344800',
                'alamat' => 'Jl. Zombie Ceria No. 3',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('ollierage'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Reine Pavolia',
                'email' => 'reine@email.com',
                'tgl_lahir' => '1998-07-17',
                'nohp' => '082112348899',
                'alamat' => 'Jl. Merak Anggun No. 9',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('reinequeen'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Amelia Watson',
                'email' => 'amelia@email.com',
                'tgl_lahir' => '1996-01-06',
                'nohp' => '087788990011',
                'alamat' => 'Jl. Detektif Waktu No. 1',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('watsondetect'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gawr Gura',
                'email' => 'gura@email.com',
                'tgl_lahir' => '1995-04-20',
                'nohp' => '081122334455',
                'alamat' => 'Jl. Laut Dalam No. 7',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('gawrshark'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shirakami Fubuki',
                'email' => 'fubuki@email.com',
                'tgl_lahir' => '1993-10-11',
                'nohp' => '089922334466',
                'alamat' => 'Jl. Serigala Putih No. 5',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('foxfriend'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Sakamata Chloe',
                'email' => 'chloe@email.com',
                'tgl_lahir' => '2000-12-24',
                'nohp' => '083312345678',
                'alamat' => 'Jl. Pembersih Laut No. 6',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('sakamata'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shirogane Noel',
                'email' => 'noel@email.com',
                'tgl_lahir' => '1994-05-15',
                'nohp' => '081999223344',
                'alamat' => 'Jl. Ksatria Baja No. 88',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('noelarmor'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kazama Iroha',
                'email' => 'iroha@email.com',
                'tgl_lahir' => '2001-03-30',
                'nohp' => '081112223334',
                'alamat' => 'Jl. Samurai Desa No. 99',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('kazamawind'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shishiro Botan',
                'email' => 'botan@email.com',
                'tgl_lahir' => '1993-09-10',
                'nohp' => '084412345666',
                'alamat' => 'Jl. Singa Siber No. 23',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('botanlion'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Roberu Shiny',
                'email' => 'Shinyroberu@email.com',
                'tgl_lahir' => '1992-06-18',
                'nohp' => '081230001111',
                'alamat' => 'Jl. Barista Hangat No. 1',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('kopiroberu'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Aruran Magni',
                'email' => 'aruran@email.com',
                'tgl_lahir' => '1990-04-04',
                'nohp' => '082220002222',
                'alamat' => 'Jl. Guru Luar Angkasa No. 12',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('aruran123'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Oga Kageyama',
                'email' => 'oga@email.com',
                'tgl_lahir' => '1989-09-09',
                'nohp' => '083330003333',
                'alamat' => 'Jl. Raja Iblis No. 3',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('ogaboss'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Rikka Violet',
                'email' => 'rikka@email.com',
                'tgl_lahir' => '1991-11-11',
                'nohp' => '084440004444',
                'alamat' => 'Jl. Ilmuwan Musik No. 21',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('gitaranrikka'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Izuru Kanade',
                'email' => 'izuru@email.com',
                'tgl_lahir' => '1993-03-03',
                'nohp' => '085550005555',
                'alamat' => 'Jl. Suara Merdu No. 10',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('izurusing'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Astel Leda',
                'email' => 'astel@email.com',
                'tgl_lahir' => '1997-12-24',
                'nohp' => '086660006666',
                'alamat' => 'Jl. Bintang Biru No. 8',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('astellight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Temma Shien',
                'email' => 'temma@email.com',
                'tgl_lahir' => '1992-10-10',
                'nohp' => '087770007777',
                'alamat' => 'Jl. Ksatria Cahaya No. 77',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('temmasword'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shien Kuro',
                'email' => 'shien@email.com',
                'tgl_lahir' => '1990-02-14',
                'nohp' => '088880008888',
                'alamat' => 'Jl. Bayangan Malam No. 2',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('shienfox'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gamma Noir',
                'email' => 'gamma@email.com',
                'tgl_lahir' => '1998-05-05',
                'nohp' => '089990009999',
                'alamat' => 'Jl. Cat Tumpah No. 17',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('gammacore'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Pikachu Volt',
                'email' => 'pikachu@email.com',
                'tgl_lahir' => '2001-08-15',
                'nohp' => '081200000001',
                'alamat' => 'Jl. Slamet Riyadi No. 1, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('pikapower'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Charmander Blaze',
                'email' => 'charmander@email.com',
                'tgl_lahir' => '2000-04-22',
                'nohp' => '081200000002',
                'alamat' => 'Jl. Karangreja No. 5, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('charmburn'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bulbasaur Vine',
                'email' => 'bulbasaur@email.com',
                'tgl_lahir' => '1999-06-30',
                'nohp' => '081200000003',
                'alamat' => 'Jl. Kalikajar No. 12, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('bulbagrow'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Squirtle Jet',
                'email' => 'squirtle@email.com',
                'tgl_lahir' => '2002-01-05',
                'nohp' => '081200000004',
                'alamat' => 'Jl. Bobotsari No. 9, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('squirtstream'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Jigglypuff Lull',
                'email' => 'jigglypuff@email.com',
                'tgl_lahir' => '1998-09-13',
                'nohp' => '081200000005',
                'alamat' => 'Jl. Kemangkon No. 3, Purbalingga',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('jigglebeat'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Eevee Morph',
                'email' => 'eevee@email.com',
                'tgl_lahir' => '2003-03-21',
                'nohp' => '081200000006',
                'alamat' => 'Jl. Purwanegara No. 14, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('eeveecode'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Snorlax Nap',
                'email' => 'snorlax@email.com',
                'tgl_lahir' => '1997-11-09',
                'nohp' => '081200000007',
                'alamat' => 'Jl. Sokaraja Tengah No. 6, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('snornap'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Gengar Shade',
                'email' => 'gengar@email.com',
                'tgl_lahir' => '1995-10-10',
                'nohp' => '081200000008',
                'alamat' => 'Jl. Karanglewas No. 8, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('ghostlaugh'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Ainz Ooal Gown',
                'email' => 'ainz@email.com',
                'tgl_lahir' => '1983-12-01',
                'nohp' => '081301000001',
                'alamat' => 'Jl. Sokanegara No. 10, Purwokerto',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('ainzsupreme'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Albedo',
                'email' => 'albedo@email.com',
                'tgl_lahir' => '1991-04-05',
                'nohp' => '081301000002',
                'alamat' => 'Jl. Bobosan No. 7, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('albedoloyal'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Shalltear Bloodfallen',
                'email' => 'shalltear@email.com',
                'tgl_lahir' => '1994-07-21',
                'nohp' => '081301000003',
                'alamat' => 'Jl. Padamara No. 9, Purbalingga',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('shalltearblood'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Demiurge',
                'email' => 'demiurge@email.com',
                'tgl_lahir' => '1987-09-13',
                'nohp' => '081301000004',
                'alamat' => 'Jl. Kalikajar No. 5, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('demiurgestrategy'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Cocytus',
                'email' => 'cocytus@email.com',
                'tgl_lahir' => '1985-11-02',
                'nohp' => '081301000005',
                'alamat' => 'Jl. Purbalingga Wetan No. 6, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('cocytuswarrior'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Aura Bella Fiora',
                'email' => 'aura@email.com',
                'tgl_lahir' => '2001-01-30',
                'nohp' => '081301000006',
                'alamat' => 'Jl. Karanglewas No. 12, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('aurabeast'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mare Bello Fiore',
                'email' => 'mare@email.com',
                'tgl_lahir' => '2001-01-30',
                'nohp' => '081301000007',
                'alamat' => 'Jl. Kejobong No. 11, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('maregentle'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Sebas Tian',
                'email' => 'sebas@email.com',
                'tgl_lahir' => '1979-03-18',
                'nohp' => '081301000008',
                'alamat' => 'Jl. Kebasen No. 4, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('sebasbutler'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Pandora’s Actor',
                'email' => 'pandora@email.com',
                'tgl_lahir' => '1995-06-10',
                'nohp' => '081301000009',
                'alamat' => 'Jl. Karangreja No. 15, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('pandoracopy'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Narberal Gamma',
                'email' => 'narberal@email.com',
                'tgl_lahir' => '1990-08-16',
                'nohp' => '081301000010',
                'alamat' => 'Jl. Baturraden No. 3, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('narberalmagic'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lucario Aura',
                'email' => 'lucario@email.com',
                'tgl_lahir' => '2001-02-02',
                'nohp' => '081200000009',
                'alamat' => 'Jl. Kalimanah No. 2, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('lucfight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mewtwo Psi',
                'email' => 'mewtwo@email.com',
                'tgl_lahir' => '1994-12-12',
                'nohp' => '081200000010',
                'alamat' => 'Jl. Pagedongan No. 1, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('psiattack'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Arthur Morgan',
                'email' => 'arthur@email.com',
                'tgl_lahir' => '1985-06-18',
                'nohp' => '081300000001',
                'alamat' => 'Jl. Baturaden No. 21, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('arthurguns'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'John Marston',
                'email' => 'john@email.com',
                'tgl_lahir' => '1983-09-12',
                'nohp' => '081300000002',
                'alamat' => 'Jl. Karangreja No. 12, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('johnoutlaw'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Sadie Adler',
                'email' => 'sadie@email.com',
                'tgl_lahir' => '1990-01-04',
                'nohp' => '081300000003',
                'alamat' => 'Jl. Kalibagor No. 7, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('sadierevenge'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Dutch van der Linde',
                'email' => 'dutch@email.com',
                'tgl_lahir' => '1978-07-23',
                'nohp' => '081300000004',
                'alamat' => 'Jl. Padamara No. 14, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('dutchdreams'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Micah Bell',
                'email' => 'micah@email.com',
                'tgl_lahir' => '1984-11-02',
                'nohp' => '081300000005',
                'alamat' => 'Jl. Kebasen No. 9, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('micahtraitor'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Charles Smith',
                'email' => 'charles@email.com',
                'tgl_lahir' => '1987-05-11',
                'nohp' => '081300000006',
                'alamat' => 'Jl. Bobotsari No. 3, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('charlesfight'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Javier Escuella',
                'email' => 'javier@email.com',
                'tgl_lahir' => '1986-08-19',
                'nohp' => '081300000007',
                'alamat' => 'Jl. Purwokerto Timur No. 6, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('javierknife'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Hosea Matthews',
                'email' => 'hosea@email.com',
                'tgl_lahir' => '1970-03-30',
                'nohp' => '081300000008',
                'alamat' => 'Jl. Bojongsari No. 5, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('hoseaplan'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Abigail Roberts',
                'email' => 'abigail@email.com',
                'tgl_lahir' => '1989-10-10',
                'nohp' => '081300000009',
                'alamat' => 'Jl. Tambak No. 2, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('abigailcare'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lenny Summers',
                'email' => 'lenny@email.com',
                'tgl_lahir' => '1992-12-12',
                'nohp' => '081300000010',
                'alamat' => 'Jl. Karanglewas No. 17, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('lennydrink'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bill Williamson',
                'email' => 'bill@email.com',
                'tgl_lahir' => '1980-04-11',
                'nohp' => '081300000011',
                'alamat' => 'Jl. Sokaraja No. 1, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('billshotgun'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Pearson',
                'email' => 'pearson@email.com',
                'tgl_lahir' => '1975-06-22',
                'nohp' => '081300000012',
                'alamat' => 'Jl. Kutasari No. 9, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('pearsoncook'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Tilly Jackson',
                'email' => 'tilly@email.com',
                'tgl_lahir' => '1993-07-08',
                'nohp' => '081300000013',
                'alamat' => 'Jl. Ajibarang No. 14, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('tillysmart'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Susan Grimshaw',
                'email' => 'susan@email.com',
                'tgl_lahir' => '1981-03-28',
                'nohp' => '081300000014',
                'alamat' => 'Jl. Kalimanah Wetan No. 3, Purbalingga',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('susantough'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Leopold Strauss',
                'email' => 'strauss@email.com',
                'tgl_lahir' => '1973-12-15',
                'nohp' => '081300000015',
                'alamat' => 'Jl. Sumpiuh No. 18, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('straussloan'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Mary-Beth Gaskill',
                'email' => 'marybeth@email.com',
                'tgl_lahir' => '1994-10-02',
                'nohp' => '081300000016',
                'alamat' => 'Jl. Bukateja No. 7, Purbalingga',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('marybethwrite'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Reverend Swanson',
                'email' => 'swanson@email.com',
                'tgl_lahir' => '1969-08-09',
                'nohp' => '081300000017',
                'alamat' => 'Jl. Banyumas Lama No. 6, Banyumas',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('swansondrink'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Uncle',
                'email' => 'uncle@email.com',
                'tgl_lahir' => '1965-01-05',
                'nohp' => '081300000018',
                'alamat' => 'Jl. Karangmoncol No. 2, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('unclelazy'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Karen Jones',
                'email' => 'karen@email.com',
                'tgl_lahir' => '1990-11-23',
                'nohp' => '081300000019',
                'alamat' => 'Jl. Purwokerto Selatan No. 5, Banyumas',
                'kelamin' => 'P',
                'sandi_hash' => Hash::make('karentrick'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
            [
                'nama' => 'Sean MacGuire',
                'email' => 'sean@email.com',
                'tgl_lahir' => '1988-09-17',
                'nohp' => '081300000020',
                'alamat' => 'Jl. Karanganyar No. 10, Purbalingga',
                'kelamin' => 'L',
                'sandi_hash' => Hash::make('seanirish'),
                'peran' => 'pelanggan',
                'created_at' => Carbon::now(),
            ],
        ];

        foreach ($data as $index => &$item) {
            $item['uid'] = sprintf('USR00000-0000-0000-0000-%012d', $index + 1);
        }

        DB::table('pengguna')->insert($data);

    }
}