export const TOPICS = {
    UPDATE_INFO: "pengguna-update-info",
    UPDATE_PASSWORD: "pengguna-update-password",
    FEEDBACK: "feedback-topic",
    ALAMAT_TAMBAH: "alamat-tujuan-topic",
    ALAMAT_EDIT: "alamat-tujuan-edit",
    ALAMAT_DELETE: "alamat-tujuan-delete",
    PENJEMPUTAN_TAMBAH: "alamat-penjemputan-topic",
    PENJEMPUTAN_EDIT: "alamat-penjemputan-edit",
    PENJEMPUTAN_DELETE: "alamat-penjemputan-delete",
    DELETE_USER: "pengguna-delete",
    ADD_USER: "pengguna-add",
    ADD_PENGIRIMAN: "pengiriman-add",
    ADD_ZONA: "zona-add",
    UPDATE_ZONA: "zona-update",
    DELETE_ZONA: "zona-delete",
};
